EMAIL = 'garnik@instigatemobile.com'
PASSWORD = 'Tester@1'
CLASS_NAME = "New Class"
GRADE_VALUE = "10"
PERIOD_VALUE = "2"
CONFIRM = "CONFIRM"
STUDENT_USERNAME = 'student{}'
ST_PASSWORD = "Student@1"
STUDENT_FNAME = "Instigate"
STUDENT_LNAME = "Mobile"
ERROR_MESSAGE = "You can not delete classes which contain students. Please move or delete the students first, then try again."